apiVersion: v1
kind: Pod
metadata:
  name: copy-data-pod
  namespace: <namespace>
spec:
  volumes:
    - name: source-volume
      persistentVolumeClaim:
        claimName: <source-claim-name>
    - name: destination-volume
      persistentVolumeClaim:
        claimName: <dest-claim-name
  containers:
    - name: data-copy-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - cp -r /source/* /destination/
      volumeMounts:
        - name: source-volume
          mountPath: /source
        - name: destination-volume
          mountPath: /destination
  restartPolicy: Never
