---
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu-systemd
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    pre_build_image: true